![alt tag](https://codelearn.io/Upload/Blog/xu-ly-du-lieu-voi-pandas-trong-python-63725977973.8696.jpg)

# **What is Pandas**
Th∆∞ vi·ªán **Pandas** cung c·∫•p c√°c c·∫•u tr√∫c d·ªØ li·ªáu hi·ªáu su·∫•t cao, d·ªÖ s·ª≠ d·ª•ng v√† c√°c c√¥ng c·ª• ph√¢n t√≠ch d·ªØ li·ªáu. C·∫•u tr√∫c d·ªØ li·ªáu ch√≠nh l√† DataFrame, c√≥ th·ªÉ coi ƒë√¢y l√† m·ªôt b·∫£ng 2D trong b·ªô nh·ªõ (gi·ªëng nh∆∞ m·ªôt b·∫£ng t√≠nh, v·ªõi t√™n c·ªôt v√† nh√£n). Nhi·ªÅu t√≠nh nƒÉng c√≥ s·∫µn trong Excel c√≥ s·∫µn theo ch∆∞∆°ng tr√¨nh, ch·∫≥ng h·∫°n nh∆∞ t·∫°o b·∫£ng t·ªïng h·ª£p, t√≠nh to√°n c·ªôt d·ª±a tr√™n c√°c c·ªôt kh√°c, v·∫Ω bi·ªÉu ƒë·ªì, v.v. C√≥ th·ªÉ nh√≥m c√°c h√†ng theo gi√° tr·ªã c·ªôt ho·∫∑c n·ªëi c√°c b·∫£ng gi·ªëng nh∆∞ trong SQL. **Pandas** c≈©ng r·∫•t gi·ªèi trong vi·ªác x·ª≠ l√Ω chu·ªói th·ªùi gian. üêº

# **Reference**
https://nbviewer.org/github/ageron/handson-ml2/blob/master/tools_pandas.ipynb

# **Pandas: Import**

Import th∆∞ vi·ªán **pandas**. H·∫ßu h·∫øt m·ªçi ng∆∞·ªùi s·ª≠ d·ª•ng n√≥ d∆∞·ªõi d·∫°ng **pd**

In [1]:
import pandas as pd

# **Saving & Loading**
> **Pandas** c√≥ th·ªÉ l∆∞u **DataFrame** v√†o c√°c ph·∫ßn ph·ª• tr·ª£ kh√°c nhau, bao g·ªìm c√°c ƒë·ªãnh d·∫°ng t·ªáp nh∆∞ $CSV, Excel, JSON, HTML$ v√† $HDF5$ ho·∫∑c v√†o c∆° s·ªü d·ªØ li·ªáu $SQL$

In [2]:
achievements = pd.DataFrame([["A+", "A", "A+", "Brilliant"],
                             ["B", "A", "A", "Good"],
                             ["B+", "B", "C", "Average"]],
                             index=["Kiet", "Toan", "Luu"],
                             columns=["Math", "English", "Physics", "achievements"])
achievements

     Math English Physics achievements
Kiet   A+       A      A+    Brilliant
Toan    B       A       A         Good
Luu    B+       B       C      Average

### **Saving**
L∆∞u v·ªõi c√°c ƒë·ªãnh d·∫°ng $CSV, HTML, JSON$

In [3]:
achievements.to_csv("achievements.csv")
achievements.to_html("achievements.html")
achievements.to_json("achievements.json")

File ƒë√£ ƒë∆∞·ª£c t·∫°o th√†nh c√¥ng

![alt tag](https://scontent.fhan14-1.fna.fbcdn.net/v/t1.15752-9/261043944_342540860969886_421972531442407130_n.png?_nc_cat=104&ccb=1-5&_nc_sid=ae9488&_nc_ohc=RlNiZOkh3YQAX_a5Fvh&_nc_ht=scontent.fhan14-1.fna&oh=5d9a7152c28c0f5934b89b09cf470bad&oe=61C50EDF)

H√£y xem qua nh·ªØng g√¨ ƒë√£ ƒë∆∞·ª£c l∆∞u

In [4]:
for filename in ("achievements.csv", "achievements.html", "achievements.json"):
    print(f'------------------ {filename} ---------------')
    with open(filename, "rt") as f:
        print(f.read())
        print()

------------------ achievements.csv ---------------
,Math,English,Physics,achievements
Kiet,A+,A,A+,Brilliant
Toan,B,A,A,Good
Luu,B+,B,C,Average


------------------ achievements.html ---------------
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Math</th>
      <th>English</th>
      <th>Physics</th>
      <th>achievements</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Kiet</th>
      <td>A+</td>
      <td>A</td>
      <td>A+</td>
      <td>Brilliant</td>
    </tr>
    <tr>
      <th>Toan</th>
      <td>B</td>
      <td>A</td>
      <td>A</td>
      <td>Good</td>
    </tr>
    <tr>
      <th>Luu</th>
      <td>B+</td>
      <td>B</td>
      <td>C</td>
      <td>Average</td>
    </tr>
  </tbody>
</table>

------------------ achievements.json ---------------
{"Math":{"Kiet":"A+","Toan":"B","Luu":"B+"},"English":{"Kiet":"A","Toan":"A","Luu":"B"},"Physics":{"Kiet":"A+","Toan":"A","Luu":"C"},"achievements":{"Kiet":"Brilliant","Toan":"Good","Luu":"Average"}}

### **Loading**

T·∫£i l·∫°i t·ªáp $CSV$ v√†o m·ªôt **DataFrame**

In [5]:
achievements_csv_load = pd.read_csv("achievements.csv", index_col = 0)
achievements_csv_load

     Math English Physics achievements
Kiet   A+       A      A+    Brilliant
Toan    B       A       A         Good
Luu    B+       B       C      Average

ƒê·ªçc d·ªØ li·ªáu t·ª´ **Github**, ·ªü ch·∫ø ƒë·ªô **view raw**

In [6]:
fish_dataset = "https://raw.githubusercontent.com/HiImKing1509/Dataset/main/fish.csv"
fish = pd.read_csv(fish_dataset, index_col=0)
fish

         Weight  Length1  Length2  Length3   Height   Width
Species
Bream     242.0     23.2     25.4     30.0  11.5200  4.0200
Bream     290.0     24.0     26.3     31.2  12.4800  4.3056
Bream     340.0     23.9     26.5     31.1  12.3778  4.6961
Bream     363.0     26.3     29.0     33.5  12.7300  4.4555
Bream     430.0     26.5     29.0     34.0  12.4440  5.1340
...         ...      ...      ...      ...      ...     ...
Smelt      12.2     11.5     12.2     13.4   2.0904  1.3936
Smelt      13.4     11.7     12.4     13.5   2.4300  1.2690
Smelt      12.2     12.1     13.0     13.8   2.2770  1.2558
Smelt      19.7     13.2     14.3     15.2   2.8728  2.0672
Smelt      19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns]

ƒê·ªçc d·ªØ li·ªáu t·ª´ **Github** th√¥ng qua vi·ªác clone ƒë∆∞·ªùng d·∫´n v·ªÅ m√°y

In [7]:
!git clone https://github.com/HiImKing1509/Dataset.git

Cloning into 'Dataset'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 18 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (18/18), done.

In [8]:
my_dataset = pd.read_csv("/content/Dataset/weather.csv")
my_dataset

      Temperature_c  Humidity  ...  Rain  Description
0         -0.555556      0.92  ...     0         Cold
1         21.111111      0.73  ...     1         Warm
2         16.600000      0.97  ...     1       Normal
3          1.600000      0.82  ...     1         Cold
4          2.194444      0.60  ...     1         Cold
...             ...       ...  ...   ...          ...
9995      10.022222      0.95  ...     1       Normal
9996       8.633333      0.64  ...     1       Normal
9997       5.977778      0.93  ...     1       Normal
9998       9.788889      0.78  ...     1       Normal
9999      11.138889      0.79  ...     1       Normal

[10000 rows x 8 columns]